# Template for creating an authorized_keys secret with envsubst.
apiVersion: v1
kind: Secret
metadata:
  name: ${SSH_AUTHORIZED_SECRET}
  namespace: ${SSH_NAMESPACE}
type: Opaque
stringData:
  authorized_keys: |
    ${SSH_AUTHORIZED_KEYS_CONTENT}
